/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import FiveCodMover.FiveCodMoverJFrame;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author nico2
 */
public class MenuJugadores extends javax.swing.JFrame {

    String[][] informacionJugadores = new String[12][9];
    Timer contadorTiempo = new Timer();
    TimerTask contadorTarea = new TimerTask() {
        @Override
        public void run() {
            msgError.setVisible(false);
            contadorTiempo.cancel();
        }
    };
   

    /**
     * Creates new form NewJFrame
     */
    public MenuJugadores() {
        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));

        numeroCamisaTF.setBackground(new Color(0, 0, 0, 0));
        numeroCamisaTF.requestFocus();
        nombreTF.setBackground(new Color(0, 0, 0, 0));
        alturaTF.setBackground(new Color(0, 0, 0, 0));
        pesoTF.setBackground(new Color(0, 0, 0, 0));

        logoNBAx2.setVisible(false);
        msgError.setVisible(false);

        placeHolderTextFields();
    }

    public void placeHolderTextFields() {
        TextPrompt numeroCamisaPH = new TextPrompt("Ingresar número de camisa", numeroCamisaTF);
        TextPrompt nombreJugadorPH = new TextPrompt("Ingresar nombre del jugador", nombreTF);
        TextPrompt alturaJugadorPH = new TextPrompt("Ingresar altura del jugador", alturaTF);
        TextPrompt pesoJugadorPH = new TextPrompt("Ingresar peso del jugador", pesoTF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        msgError = new javax.swing.JLabel();
        CM = new javax.swing.JLabel();
        KG = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        alturaTF = new javax.swing.JTextField();
        pesoTF = new javax.swing.JTextField();
        numeroCamisaTF = new javax.swing.JTextField();
        numeroCamisa = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        altura = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        guardar = new javax.swing.JLabel();
        numeroJugador = new javax.swing.JLabel();
        mostrarInformacion = new javax.swing.JLabel();
        inscribirInformacio = new javax.swing.JLabel();
        inscribirJugadores = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        logoNBAx2 = new javax.swing.JLabel();
        logoNBA = new javax.swing.JLabel();
        shapeBackground1 = new javax.swing.JLabel();
        shapeBackground = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgError.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        msgError.setForeground(new java.awt.Color(255, 102, 102));
        msgError.setText("Por favor no dejar casillas vacias e ingresar numeros validos");
        jPanel1.add(msgError, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 710, 30));

        CM.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CM.setForeground(new java.awt.Color(255, 255, 255));
        CM.setText("Cm");
        jPanel1.add(CM, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, -1, 40));

        KG.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        KG.setForeground(new java.awt.Color(255, 255, 255));
        KG.setText("Kg");
        jPanel1.add(KG, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, -1, 40));

        nombreTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombreTF.setForeground(new java.awt.Color(255, 255, 255));
        nombreTF.setBorder(null);
        nombreTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTFFocusLost(evt);
            }
        });
        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });
        jPanel1.add(nombreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 410, 40));

        alturaTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alturaTF.setForeground(new java.awt.Color(255, 255, 255));
        alturaTF.setBorder(null);
        alturaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alturaTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alturaTFFocusLost(evt);
            }
        });
        alturaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaTFActionPerformed(evt);
            }
        });
        jPanel1.add(alturaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 410, 40));

        pesoTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesoTF.setForeground(new java.awt.Color(255, 255, 255));
        pesoTF.setBorder(null);
        pesoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pesoTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesoTFFocusLost(evt);
            }
        });
        pesoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTFActionPerformed(evt);
            }
        });
        jPanel1.add(pesoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 410, 40));

        numeroCamisaTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeroCamisaTF.setForeground(new java.awt.Color(255, 255, 255));
        numeroCamisaTF.setBorder(null);
        numeroCamisaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroCamisaTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroCamisaTFFocusLost(evt);
            }
        });
        numeroCamisaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCamisaTFActionPerformed(evt);
            }
        });
        jPanel1.add(numeroCamisaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 410, 40));

        numeroCamisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/numeroCamisa.png"))); // NOI18N
        jPanel1.add(numeroCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/nombre.png"))); // NOI18N
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        altura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/altura.png"))); // NOI18N
        jPanel1.add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        peso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/peso.png"))); // NOI18N
        jPanel1.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/guardarBTN.png"))); // NOI18N
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarMouseExited(evt);
            }
        });
        guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guardarKeyPressed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, -1, -1));

        numeroJugador.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        numeroJugador.setText("1");
        jPanel1.add(numeroJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, -1, 80));

        mostrarInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarInformacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarInformacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarInformacionMouseExited(evt);
            }
        });
        jPanel1.add(mostrarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 40));

        inscribirInformacio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscribirInformacioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inscribirInformacioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inscribirInformacioMouseExited(evt);
            }
        });
        jPanel1.add(inscribirInformacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 300, 40));

        inscribirJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscribirJugadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inscribirJugadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inscribirJugadoresMouseExited(evt);
            }
        });
        jPanel1.add(inscribirJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, 40));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/Menu.png"))); // NOI18N
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 320, 240));

        logoNBAx2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/logoNBAx2.png"))); // NOI18N
        logoNBAx2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoNBAx2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoNBAx2MouseExited(evt);
            }
        });
        jPanel1.add(logoNBAx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 200, 180));

        logoNBA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/logoNBA.png"))); // NOI18N
        logoNBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoNBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoNBAMouseExited(evt);
            }
        });
        jPanel1.add(logoNBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 190, 180));

        shapeBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/shapeBackground.png"))); // NOI18N
        jPanel1.add(shapeBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        shapeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/shapeBackground.png"))); // NOI18N
        jPanel1.add(shapeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, -500, -1, -1));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/Volver.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 150, 50));

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/Backgorund.png"))); // NOI18N
        jPanel1.add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscribirJugadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscribirJugadoresMouseEntered
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/inscribirJugadores.png")));
    }//GEN-LAST:event_inscribirJugadoresMouseEntered

    private void inscribirJugadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscribirJugadoresMouseExited
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/Menu.png")));
    }//GEN-LAST:event_inscribirJugadoresMouseExited

    private void inscribirInformacioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscribirInformacioMouseEntered
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/inscribirEquipo.png")));
    }//GEN-LAST:event_inscribirInformacioMouseEntered

    private void inscribirInformacioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscribirInformacioMouseExited
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/Menu.png")));
    }//GEN-LAST:event_inscribirInformacioMouseExited

    private void mostrarInformacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarInformacionMouseEntered
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/mostrarInformacion.png")));
    }//GEN-LAST:event_mostrarInformacionMouseEntered

    private void mostrarInformacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarInformacionMouseExited
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/Menu.png")));
    }//GEN-LAST:event_mostrarInformacionMouseExited

    private void logoNBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoNBAMouseEntered
        logoNBA.setVisible(false);
        logoNBAx2.setVisible(true);
    }//GEN-LAST:event_logoNBAMouseEntered

    private void logoNBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoNBAMouseExited
        logoNBA.setVisible(true);
        logoNBAx2.setVisible(false);
    }//GEN-LAST:event_logoNBAMouseExited

    private void logoNBAx2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoNBAx2MouseEntered
        logoNBA.setVisible(false);
        logoNBAx2.setVisible(true);
    }//GEN-LAST:event_logoNBAx2MouseEntered

    private void logoNBAx2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoNBAx2MouseExited
        logoNBA.setVisible(true);
        logoNBAx2.setVisible(false);
    }//GEN-LAST:event_logoNBAx2MouseExited

    private void inscribirJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscribirJugadoresMouseClicked

    }//GEN-LAST:event_inscribirJugadoresMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/VolverHover.png")));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/Volver.png")));
    }//GEN-LAST:event_volverMouseExited

    private void numeroCamisaTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroCamisaTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCamisaTFFocusGained

    private void numeroCamisaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroCamisaTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCamisaTFFocusLost

    private void numeroCamisaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCamisaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCamisaTFActionPerformed

    private void nombreTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFFocusGained

    private void nombreTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFFocusLost

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void alturaTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alturaTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTFFocusGained

    private void alturaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alturaTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTFFocusLost

    private void alturaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTFActionPerformed

    private void pesoTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesoTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTFFocusGained

    private void pesoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesoTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTFFocusLost

    private void pesoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTFActionPerformed

    private void guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseEntered
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/guardarHover.png")));
    }//GEN-LAST:event_guardarMouseEntered

    private void guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseExited
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/guardarBTN.png")));
    }//GEN-LAST:event_guardarMouseExited

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        MenuInicio menuInicio = new MenuInicio();
        menuInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverMouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        String numeroCamisaJugador = numeroCamisaTF.getText();
        String alturaJugador = alturaTF.getText();
        String nombreJugador = nombreTF.getText();
        String pesoJugador = pesoTF.getText();

        numeroCamisaTF.requestFocus();
        


        
        //Validar que no son vacios
        if (numeroCamisaJugador.isEmpty() || alturaJugador.isEmpty() || nombreJugador.isEmpty() || pesoJugador.isEmpty() || ( !numeroCamisaJugador.matches("[0-9]+") || numeroCamisaJugador == null ) || ( !alturaJugador.matches("[0-9]+") || alturaJugador == null ) || ( !pesoJugador.matches("[0-9]+") || pesoJugador == null )) {
            msgError.setVisible(true);
            contadorTiempo.schedule(contadorTarea, 2000);
        } else {
            int iteracionArreglo = Integer.parseInt(numeroJugador.getText());
            iteracionArreglo -= 1;

            String[] jugadoresEstadisticas = {numeroCamisaJugador, nombreJugador, alturaJugador, pesoJugador, "0", "0", "0", "0", "0"};
            informacionJugadores[iteracionArreglo] = jugadoresEstadisticas;

            int iteracionNumero = Integer.parseInt(numeroJugador.getText());
            iteracionNumero += 1;

            if (iteracionNumero < 13) {
                String iteracionNumeroLabel = Integer.toString(iteracionNumero);
                numeroJugador.setText(iteracionNumeroLabel);
            }

            numeroCamisaTF.setText(null);
            nombreTF.setText(null);
            alturaTF.setText(null);
            pesoTF.setText(null);

            if (iteracionArreglo == 11) {
                guardar.setVisible(false);
                MenuPersonal personalEquipo = new MenuPersonal();
                personalEquipo.setDataEquipo(informacionJugadores);
                personalEquipo.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_guardarMouseClicked

    private void guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guardarKeyPressed

    }//GEN-LAST:event_guardarKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void inscribirInformacioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscribirInformacioMouseClicked
        MenuPartido inscribirJugadores = new MenuPartido();
        inscribirJugadores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inscribirInformacioMouseClicked

    private void mostrarInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarInformacionMouseClicked
       MenuEstadisticas menuEstadisticas = new MenuEstadisticas();
        menuEstadisticas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mostrarInformacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJugadores().setVisible(true);
            }
        });
    }

    public String[][] getInfoJugadores() {
        return informacionJugadores;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CM;
    private javax.swing.JLabel KG;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel altura;
    public static javax.swing.JTextField alturaTF;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel guardar;
    private javax.swing.JLabel inscribirInformacio;
    private javax.swing.JLabel inscribirJugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoNBA;
    private javax.swing.JLabel logoNBAx2;
    private javax.swing.JLabel mostrarInformacion;
    private javax.swing.JLabel msgError;
    private javax.swing.JLabel nombre;
    public static javax.swing.JTextField nombreTF;
    private javax.swing.JLabel numeroCamisa;
    public static javax.swing.JTextField numeroCamisaTF;
    private javax.swing.JLabel numeroJugador;
    private javax.swing.JLabel peso;
    public static javax.swing.JTextField pesoTF;
    private javax.swing.JLabel shapeBackground;
    private javax.swing.JLabel shapeBackground1;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
